import seturiImg from '../img/seturi/sushi-set.jpg'
const seturiProducts = [
  {
    name: "Set",
    price: 100,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Cucumbers roll - 8 bucăți",
      "Philadelphia cu somon grill - 8 bucăți",
      "Canada - 8 bucăți",
      "Tempura cu surimi - 8 bucăți",

    ],
    id: 0,
    category: "seturi",
    weight: '1300g',
  },
  {
    name: "Set 2",
    price: 150,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Canada - 8 bucăți",
      "Tempura cu surimi - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 1,
    category: "seturi",
    weight: '1100g',
  },
  {
    name: "Set 3",
    price: 250,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "Canada - 8 bucăți",
      "Tempura cu surimi - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 2,
    category: "seturi",
    weight: '1200g',
  },
  {
    name: "Set 4",
    price: 350,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Cucumbers roll - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 3,
    category: "seturi",
    weight: '1300g',
  },
  {
    name: "Set 5",
    price: 450,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Cucumbers roll - 8 bucăți",
      "Philadelphia cu somon grill - 8 bucăți",
      "Canada - 8 bucăți",
      "Tempura cu surimi - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 4,
    category: "seturi",
    weight: '1400g',
  },
  {
    name: "Set 6",
    price: 550,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Cucumbers roll - 8 bucăți",
      "Philadelphia cu somon grill - 8 bucăți",
      "Canada - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 5,
    category: "seturi",
    weight: '1500g',
  },
  {
    name: "Set 7",
    price: 650,
    currency: "MDL",
    img: seturiImg,
    ingredients: [
      "California cu ton - 8 bucăți",
      "Philadelphia cu crevete - 8 bucăți",
      "Cucumbers roll - 8 bucăți",
      "Philadelphia cu somon grill - 8 bucăți",
      "Canada - 8 bucăți",
      "Philadelphia clasic - 8 bucăți",
    ],
    id: 6,
    category: "seturi",
    weight: '1600g',
  },
];

export default seturiProducts